name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_BOT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
                        
            ${{ github.event.commits[0].message }}
