name: notify TG while push
on: 
  push:
    branches:
      - 'main'
      - 'hot-fix**'
jobs:
  notify-TG:
    runs-on: ubuntu-latest
    steps:
      - name: notify TG
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_BOT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          message: |
            ${{ github.actor }} pushed to ${{ github.ref }}:
                        
            ${{ github.event.head_commit.message }}
